apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedSecret
  metadata:
    name: test-secret
    namespace: test-namespace
  spec:
    template:
      data:
        A: YWxhIG1hIGtvdGE=
      type: Opaque
