apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedSecret
metadata:
  name: test-secret
  namespace: test-namespace
spec:
  template:
    data:
      A: YWxhIG1hIGtvdGE=
    type: Opaque
  placement:
    clusterNames:
    - us-east
    - ap-north
  overrides:
  - clusterName: us-east
    clusterOverrides:
    - path: data
      value:
        A: null
