apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedSecretOverride
  metadata:
    name: test-secret
    namespace: test-namespace
  spec:
    Overrides:
    - clustername: us-east
      data:
