apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedReplicaSet
  metadata:
    name: test-replicaset
    namespace: test-namespace
  spec:
    template:
      metadata:
        labels:
          foo: bar
      spec:
        replicas: 3
        selector:
          matchLabels:
            foo: bar
        template:
          metadata:
            labels:
              foo: bar
          spec:
            containers:
            - image: nginx
              imagePullPolicy: Always
              name: nginx
