apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: test-service
    namespace: test-namespace
  spec:
    template:
      metadata:
        labels:
          run: nginx
        name: nginx
      spec:
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 80
          name: http
        - port: 443
          protocol: TCP
          name: https
        selector:
          run: nginx
        type: NodePort
