apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentOverride
  metadata:
    name: test-deployment
    namespace: test-namespace
  spec:
    overrides:
    - clustername: us-east
      replicas: 5
    - clustername: eu-central
      replicas: 9
