apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedReplicaSetPlacement
  metadata:
    name: test-replicaset
    namespace: test-namespace
  spec:
    clusternames:
    - cluster1
    - cluster2
