apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: test-service
    namespace: test-namespace
  spec:
    clusternames:
    - us-east
    - eu-central
    - ap-north
