apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.0
  name: federatedreplicasetstatuses.status.federation.k8s.io
spec:
  group: status.federation.k8s.io
  names:
    kind: FederatedReplicaSetStatus
    plural: federatedreplicasetstatuses
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties: {}
          type: object
        status:
          type: object
          properties:
            federatedClusterStatus:
              type: array
              items:
                type: object
                properties:
                  clusterName:
                    type: string
                  readyReplicas:
                    type: integer
                    format: int32
                  replicas:
                    type: integer
                    format: int32
              required:
              - replicas
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
