apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedReplicaSet
  metadata:
    name: test-replicaset
    namespace: test-namespace
  spec:
    template:
      metadata:
        labels:
          run: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            run: nginx
        template:
          metadata:
            labels:
              run: nginx
          spec:
            containers:
            - image: nginx
              name: nginx
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
              - containerPort: 80
