/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-sigs/federation-v2/pkg/apis/status/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFederatedReplicaSetStatuses implements FederatedReplicaSetStatusInterface
type FakeFederatedReplicaSetStatuses struct {
	Fake *FakeStatusV1alpha1
	ns   string
}

var federatedreplicasetstatusesResource = schema.GroupVersionResource{Group: "status.federation.k8s.io", Version: "v1alpha1", Resource: "federatedreplicasetstatuses"}

var federatedreplicasetstatusesKind = schema.GroupVersionKind{Group: "status.federation.k8s.io", Version: "v1alpha1", Kind: "FederatedReplicaSetStatus"}

// Get takes name of the federatedReplicaSetStatus, and returns the corresponding federatedReplicaSetStatus object, and an error if there is any.
func (c *FakeFederatedReplicaSetStatuses) Get(name string, options v1.GetOptions) (result *v1alpha1.FederatedReplicaSetStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(federatedreplicasetstatusesResource, c.ns, name), &v1alpha1.FederatedReplicaSetStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedReplicaSetStatus), err
}

// List takes label and field selectors, and returns the list of FederatedReplicaSetStatuses that match those selectors.
func (c *FakeFederatedReplicaSetStatuses) List(opts v1.ListOptions) (result *v1alpha1.FederatedReplicaSetStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(federatedreplicasetstatusesResource, federatedreplicasetstatusesKind, c.ns, opts), &v1alpha1.FederatedReplicaSetStatusList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FederatedReplicaSetStatusList{}
	for _, item := range obj.(*v1alpha1.FederatedReplicaSetStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedReplicaSetStatuses.
func (c *FakeFederatedReplicaSetStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(federatedreplicasetstatusesResource, c.ns, opts))

}

// Create takes the representation of a federatedReplicaSetStatus and creates it.  Returns the server's representation of the federatedReplicaSetStatus, and an error, if there is any.
func (c *FakeFederatedReplicaSetStatuses) Create(federatedReplicaSetStatus *v1alpha1.FederatedReplicaSetStatus) (result *v1alpha1.FederatedReplicaSetStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(federatedreplicasetstatusesResource, c.ns, federatedReplicaSetStatus), &v1alpha1.FederatedReplicaSetStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedReplicaSetStatus), err
}

// Update takes the representation of a federatedReplicaSetStatus and updates it. Returns the server's representation of the federatedReplicaSetStatus, and an error, if there is any.
func (c *FakeFederatedReplicaSetStatuses) Update(federatedReplicaSetStatus *v1alpha1.FederatedReplicaSetStatus) (result *v1alpha1.FederatedReplicaSetStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(federatedreplicasetstatusesResource, c.ns, federatedReplicaSetStatus), &v1alpha1.FederatedReplicaSetStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedReplicaSetStatus), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedReplicaSetStatuses) UpdateStatus(federatedReplicaSetStatus *v1alpha1.FederatedReplicaSetStatus) (*v1alpha1.FederatedReplicaSetStatus, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(federatedreplicasetstatusesResource, "status", c.ns, federatedReplicaSetStatus), &v1alpha1.FederatedReplicaSetStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedReplicaSetStatus), err
}

// Delete takes name of the federatedReplicaSetStatus and deletes it. Returns an error if one occurs.
func (c *FakeFederatedReplicaSetStatuses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(federatedreplicasetstatusesResource, c.ns, name), &v1alpha1.FederatedReplicaSetStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedReplicaSetStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(federatedreplicasetstatusesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FederatedReplicaSetStatusList{})
	return err
}

// Patch applies the patch and returns the patched federatedReplicaSetStatus.
func (c *FakeFederatedReplicaSetStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FederatedReplicaSetStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(federatedreplicasetstatusesResource, c.ns, name, data, subresources...), &v1alpha1.FederatedReplicaSetStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedReplicaSetStatus), err
}
